print "Hello World!"
print "Hello Again"
print "I like typing this."
print "This is fun."
print "Yay! Printing."
print "I'd much rather you 'not'."
print 'I "said" do not touch this.'
print "-- -- -- -- -- -- -- -- --"
print " Study Drills"
print "-- -- -- -- -- -- -- -- --"
print "1. Print another line."
print ""
print "2. Make your script print only one of the lines."
print "3. Put a # (octothorpe) character at the beginning of a line.  What did it do?  Try to find out what this character does."
print "hint: It turns the line of code into a comment that can be used to explain bits of code without actually running the line itself."